apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applicationName }}
spec:
  destination:
    namespace: {{ .Values.targetNamespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    path: {{ .Values.repoPath }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
